# Generated by Django 4.1.3 on 2023-08-20 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Post",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_ts",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Created TimeStamp"
                    ),
                ),
                (
                    "updated_ts",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Updated TimeStamp"
                    ),
                ),
                ("name", models.TextField()),
                ("prompt", models.TextField()),
                ("img_url", models.TextField()),
            ],
            options={
                "ordering": ("created_ts", "updated_ts"),
                "abstract": False,
            },
        ),
    ]
